export enum ListenedEvent {
  CONNECT = 'CONNECT',
  SEND_PRIVATE_MESSAGE = 'SEND_PRIVATE_MESSAGE',
  SEND_GROUP_MESSAGE = 'SEND_GROUP_MESSAGE',
  CREATE_ROOM = 'CREATE_ROOM',
  JOIN_ROOM = 'JOIN_ROOM',
  LEAVE_ROOM = 'LEAVE_ROOM',
}

export enum EmitedEvent {
  PROCESS_SUCCESSFULLY = 'PROCESS_SUCCESSFULLY',
  PROCESS_FAILED = 'PROCESS_FAILED',
  UPDATE_FRIEND_STATUS = 'UPDATE_FRIEND_STATUS',
  RECEIVE_FRIEND_LIST = 'RECEIVE_FRIEND_LIST',
  RECEIVE_PRIVATE_MESSAGE = 'RECEIVE_PRIVATE_MESSAGE',
  RECEIVE_GROUP_MESSAGE = 'RECEIVE_GROUP_MESSAGE',
  UPDATE_GROUP_MEMBER = 'UPDATE_GROUP_MEMBER',
}
