export enum Event {
  FAILURE = 'FAILURE',
  SUCCESS = 'SUCCESS',
  CONNECTION = 'CONNECTION',
  FRIEND_STATUS = 'FRIEND_STATUS',
  FRIEND_LIST = 'FRIEND_LIST',
  PRIVATE_MESSAGE = 'PRIVATE_MESSAGE',
}
