export enum Event {
  EXCEPTION = 'EXCEPTION',
  FRIEND_STATUS = 'FRIEND_STATUS',
  FRIEND_LIST = 'FRIEND_LIST',
  PRIVATE_MESSAGE = 'PRIVATE_MESSAGE',
  FAILED_PRIVATE_MESSAGE = 'FAILED_PRIVATE_MESSAGE',
}
